-- CreateEnum
CREATE TYPE "CopyMode" AS ENUM ('FIXED_LOT', 'MULTIPLIER', 'BALANCE_PROPORTIONAL', 'EQUITY_PROPORTIONAL');

-- AlterTable
ALTER TABLE "masters" ADD COLUMN     "balance" DECIMAL(18,2),
ADD COLUMN     "equity" DECIMAL(18,2);

-- AlterTable
ALTER TABLE "slaves" ADD COLUMN     "balance" DECIMAL(18,2),
ADD COLUMN     "copy_mode" "CopyMode" NOT NULL DEFAULT 'MULTIPLIER',
ADD COLUMN     "equity" DECIMAL(18,2),
ADD COLUMN     "fixed_lot" DECIMAL(18,2),
ADD COLUMN     "lot_step" DECIMAL(18,2) NOT NULL DEFAULT 0.01,
ADD COLUMN     "max_lot" DECIMAL(18,2) NOT NULL DEFAULT 10.0,
ADD COLUMN     "min_lot" DECIMAL(18,2) NOT NULL DEFAULT 0.01,
ADD COLUMN     "multiplier" DECIMAL(10,4) NOT NULL DEFAULT 1.0;
